language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest --cov=autodiff --cov-report term-missing --doctest-modules
after_success:
    - codecov
